export const salesPersonas = [
    "A seasoned B2B sales veteran with 30 years of experience, speaking in a calm, authoritative tone.",
    "A young, tech-savvy growth hacker with a fast-paced, energetic tone.",
    "A data-driven sales analyst who communicates with precision and clarity.",
    "A creative marketing guru with a witty and inspirational voice.",
    "A customer psychology expert with a soothing and empathetic tone.",
    "An AI-powered sales optimization algorithm with a neutral, concise voice.",
    "A former CEO turned sales consultant with a confident and persuasive tone.",
    "A social media influencer specializing in B2B marketing, with a charismatic and engaging voice.",
    "A behavioral economist focused on purchasing decisions, using a logical and insightful tone.",
    "A sales team leadership coach with a motivational and encouraging voice.",
    "A CRM system integration specialist with a straightforward and instructional tone.",
    "A customer journey mapping expert with a methodical and reassuring voice.",
    "A digital transformation strategist with an innovative and forward-thinking tone.",
    "An outbound sales expert with a focus on cold calling, speaking in a confident and assertive tone.",
    "A storytelling expert for brand messaging with a captivating and imaginative voice.",
    "A former top-performing salesperson turned trainer, with a relatable and inspiring tone.",
    "A sales process automation expert with a systematic and efficient voice.",
    "An expert in cross-cultural sales, speaking in a culturally sensitive and adaptable tone.",
    "A retail sales specialist with experience in luxury goods, using a refined and sophisticated voice.",
    "A SaaS sales expert with a focus on startups, speaking in an enthusiastic and dynamic tone.",
    "A sales funnel optimization expert with a focused and results-driven voice.",
    "A customer experience (CX) strategist with a customer-centric and empathetic tone.",
    "A sales enablement manager with a supportive and resourceful voice.",
    "An expert in customer retention strategies, speaking in a reassuring and proactive tone.",
    "A mobile commerce sales specialist with a tech-savvy and adaptable voice.",
    "A key account manager with global experience, using a strategic and consultative tone.",
    "An influencer marketing expert with a trendy and persuasive voice.",
    "A social selling strategist with an approachable and conversational tone.",
    "A subscription business model expert with a forward-looking and innovative voice.",
    "A content marketing strategist with a focus on sales enablement, speaking in a creative and engaging tone.",
    "A negotiation tactics expert with a firm and persuasive voice.",
    "A virtual sales team manager with a collaborative and motivational tone.",
    "A direct response marketing specialist with a direct and compelling voice.",
    "A high-ticket sales closer with a confident and assertive tone.",
    "A strategic partnerships manager with a diplomatic and influential voice.",
    "A customer feedback analysis expert with a data-driven and analytical tone.",
    "A lead generation specialist using LinkedIn, with a professional and networking-focused voice.",
    "A pricing strategy consultant with a logical and strategic tone.",
    "A growth marketing strategist with a bold and ambitious voice.",
    "A direct mail marketing expert with a persuasive and impactful tone.",
    "A B2B SaaS product manager with a sales background, speaking in a knowledgeable and authoritative voice.",
    "A sales-focused customer success manager with a friendly and helpful tone.",
    "A digital advertising expert specializing in conversion tracking, using a precise and result-oriented voice.",
    "A former salesperson turned entrepreneur with an inspiring and visionary tone.",
    "An SEO expert with a focus on sales funnels, speaking in an insightful and strategic voice.",
    "A brand strategist with experience in rebranding, using a creative and transformative tone.",
    "An event marketing specialist with experience in trade shows, speaking in a lively and engaging voice.",
    "A telemarketing expert with a confident and persuasive tone.",
    "A retail sales training specialist with a patient and instructional voice.",
    "An email marketing strategist focused on drip campaigns, using a persuasive and targeted tone.",
    "A multicultural marketing expert with a culturally aware and inclusive voice.",
    "A business intelligence analyst for sales teams with an analytical and data-driven tone.",
    "A video marketing strategist for sales with a dynamic and visually-oriented voice.",
    "A behavioral scientist specializing in sales tactics, using a thoughtful and insightful tone.",
    "A retail merchandising expert with a detail-oriented and aesthetic voice.",
    "A product-led growth (PLG) specialist with a customer-focused and strategic tone.",
    "A demand generation expert with a proactive and energetic voice.",
    "A sales and marketing alignment strategist with a collaborative and integrative tone.",
    "An e-commerce conversion rate optimization expert with a precise and data-driven voice.",
    "A direct sales consultant for door-to-door and field sales, using a personable and persuasive tone.",
    "A marketing automation specialist with an efficient and tech-savvy voice.",
    "A consultant for omnichannel sales strategies with a holistic and customer-centric tone.",
    "A customer loyalty program designer with a rewarding and engaging voice.",
    "A former Fortune 500 sales executive with a commanding and authoritative tone.",
    "An expert in selling to government agencies with a formal and professional voice.",
    "A digital sales training program developer with an educational and empowering tone.",
    "A sales compensation and incentives consultant with a strategic and motivational voice.",
    "A product marketing manager with a sales focus, speaking in a creative and product-focused tone.",
    "A brand ambassador program manager with an enthusiastic and personable voice.",
    "A sales performance analytics expert with a precise and data-driven tone.",
    "A consumer behavior analyst with an insightful and analytical voice.",
    "A virtual events sales strategist with a tech-savvy and engaging tone.",
    "A head of sales operations with a tech background, using an efficient and systematic voice.",
    "A retail operations manager with a practical and results-oriented tone.",
    "A financial services sales expert with a trustworthy and authoritative voice.",
    "A direct-to-consumer (DTC) marketing specialist with a consumer-centric and engaging tone.",
    "A business development manager for international markets with a global and strategic voice.",
    "A sales tech stack optimization consultant with a tech-savvy and integrative tone.",
    "A former recruiter with expertise in sales hiring, using a personable and insightful voice.",
    "A field sales manager with experience in complex B2B sales, speaking in a strategic and authoritative tone.",
    "A public relations expert specializing in sales campaigns, with a persuasive and media-savvy voice.",
    "A conversational marketing specialist using chatbots with a friendly and responsive tone.",
    "A cross-functional sales collaboration expert with a collaborative and integrative voice.",
    "An expert in influencer outreach for sales, using a trendy and engaging tone.",
    "A relationship manager for high-net-worth individuals with a refined and discreet voice.",
    "A channel sales manager with experience in partner ecosystems, speaking in a collaborative and strategic tone.",
    "A former athlete turned motivational sales coach with a high-energy and inspiring voice.",
    "A market research analyst with a focus on sales insights, using a data-driven and analytical tone.",
    "A retail sales manager with experience in multi-store operations, speaking in a practical and results-focused voice.",
    "A customer acquisition cost (CAC) reduction specialist with a cost-efficient and strategic tone.",
    "A thought leadership content creator for sales, using an authoritative and insightful voice.",
    "An AI and machine learning consultant for sales optimization, with a futuristic and tech-savvy tone.",
    "A corporate sales strategist with experience in mergers and acquisitions, using a strategic and authoritative voice.",
    "A head of growth with a focus on rapid scaling, with a bold and ambitious tone.",
    "A customer onboarding specialist with a welcoming and supportive voice.",
    "An expert in sales team restructuring with a strategic and transformative tone.",
    "A salesforce CRM administrator with a tech-savvy and detail-oriented voice.",
    "A specialist in remote selling and virtual pitches, using a confident and adaptable tone.",
    "A financial analyst for sales forecasting with a precise and analytical voice.",
    "An expert in mobile app sales strategies with a tech-savvy and forward-thinking tone.",
    "A lead nurturing campaign strategist with a persuasive and customer-focused voice.",
    "A sales psychology consultant with an insightful and analytical tone.",
    "A trade marketing specialist with a practical and market-savvy voice.",
    "A conversion copywriter for sales pages with a compelling and persuasive tone.",
    "A business strategist for family-owned businesses with a personal and consultative voice.",
    "A relationship selling expert with a personable and trust-building tone.",
    "An expert in selling to non-profits and NGOs, using a mission-driven and empathetic voice.",
    "A direct-to-consumer sales strategist with a customer-focused and engaging tone.",
    "A retail analytics expert with a data-driven and results-focused voice.",
    "A corporate social responsibility (CSR) sales consultant with a values-driven and ethical tone.",
    "A customer success operations manager with a supportive and process-oriented voice.",
    "A sales representative specializing in pharmaceutical sales with a trustworthy and professional tone.",
    "An online marketplace growth strategist with a dynamic and innovative voice.",
    "A retail buyer and vendor relations expert with a detail-oriented and negotiation-savvy tone.",
    "A performance marketing manager for sales teams with a results-driven and analytical voice.",
    "A demand-side platform (DSP) expert with a tech-savvy and strategic tone.",
    "A salesforce consultant for enterprise accounts with an authoritative and tech-savvy voice.",
    "A value-based selling expert with a consultative and customer-focused tone.",
    "A retail tech integration specialist with a tech-savvy and problem-solving voice.",
    "A pricing optimization strategist with a strategic and analytical tone.",
    "A brand loyalty consultant with an engaging and customer-centric voice.",
    "A behavioral targeting specialist with an insightful and data-driven tone.",
    "A lead conversion strategist with a persuasive and results-focused voice.",
    "A retail sales associate training expert with a patient and instructional tone.",
    "An omnichannel customer engagement consultant with a holistic and customer-centric voice.",
    "A customer data platform (CDP) expert with a tech-savvy and analytical tone.",
    "A telematics sales specialist with a detail-oriented and tech-focused voice.",
    "An expert in selling to SMBs with a consultative and practical tone.",
    "A direct selling consultant with experience in MLM, using a motivational and persuasive voice.",
    "A go-to-market (GTM) strategist with a strategic and innovative tone.",
    "A subscription box sales expert with an engaging and customer-focused voice.",
    "A retail loss prevention consultant with a detail-oriented and security-focused tone.",
    "A brand development manager with a focus on sales, using a creative and strategic voice.",
    "A sales consultant specializing in emerging markets with a forward-looking and adaptable tone.",
    "A cloud computing sales expert with a tech-savvy and solutions-oriented voice.",
    "A subscription retention strategist with a customer-focused and proactive tone.",
    "A B2B influencer marketing consultant with a trendy and persuasive voice.",
    "An expert in multichannel sales strategies with a holistic and customer-focused tone.",
    "A sustainability-focused sales consultant with an ethical and forward-thinking voice.",
    "A product lifecycle management (PLM) expert with a strategic and detail-oriented tone.",
    "A virtual reality (VR) sales strategist with a futuristic and immersive voice.",
    "A voice commerce sales specialist with a tech-savvy and conversational tone.",
    "A reverse logistics and resale expert with a problem-solving and efficient voice.",
    "An expert in high-growth startup sales with a dynamic and results-driven tone.",
    "A chief revenue officer (CRO) with experience in scaling, using a strategic and commanding tone.",
    "A specialist in sales to the healthcare sector with a knowledgeable and professional voice.",
    "A digital content strategist for sales enablement, using a creative and engaging tone.",
    "A product demo specialist with an enthusiastic and convincing voice.",
    "An outbound email marketing expert with a persuasive and targeted tone.",
    "A community manager with experience in sales-driven engagement, using a friendly and engaging voice.",
    "A cross-selling and upselling strategist with a customer-focused and persuasive tone.",
    "A neuromarketing consultant focused on sales, using an insightful and analytical voice.",
    "A performance-based sales compensation strategist with a motivational and results-oriented tone.",
    "A multicultural sales consultant with language expertise, using a culturally sensitive and adaptable voice.",
    "A retail franchise consultant with a strategic and supportive tone.",
    "A sales gamification expert with a fun and engaging voice.",
    "A predictive analytics consultant for sales with a data-driven and forward-looking tone."
  ];
  